export const PitchEvent = {
    EXPIRE_BOOKING: "EXPIRE_BOOKING"
} as const;

export type PitchEvent = (typeof PitchEvent)[keyof typeof PitchEvent];

export type PitchJobPayload = {
    pitchId: string;
    bookingId: string;
    event: PitchEvent;
};

const pitches = [
    { en: { name: "Al Nour Sports Complex", description: "A well-maintained sports facility offering multiple grounds for football and other sports. Ideal for casual and competitive play alike." }, ar: { name: "مجمع النور الرياضي", description: "مرفق رياضي مجهز بملاعب متعددة لكرة القدم وغيرها من الرياضات. مثالي للهواة والمحترفين على حد سواء." } },
    { en: { name: "Victory Arena", description: "One of the top-rated venues in the city, featuring premium turf and excellent facilities for players of all levels." }, ar: { name: "أرينا النصر", description: "من أفضل الملاعب في المدينة، تتميز بنجيلة عالية الجودة ومرافق ممتازة لجميع المستويات." } },
    { en: { name: "Elite Sports Club", description: "A premium destination for football enthusiasts, offering state-of-the-art grounds with full amenities." }, ar: { name: "نادي النخبة الرياضي", description: "وجهة متميزة لعشاق كرة القدم، توفر ملاعب حديثة بكامل المرافق والخدمات." } },
    { en: { name: "Green Field Stadium", description: "Spacious grounds with natural grass and modern lighting, perfect for evening matches and weekend tournaments." }, ar: { name: "ملعب الميدان الأخضر", description: "ملاعب واسعة بنجيلة طبيعية وإضاءة حديثة، مثالية للمباريات المسائية وبطولات نهاية الأسبوع." } },
    { en: { name: "Champions Ground", description: "Built for serious players, this facility combines professional-grade turf with a welcoming atmosphere for all." }, ar: { name: "ملعب الأبطال", description: "مصمم للاعبين الجادين، يجمع هذا المرفق بين نجيلة احترافية وأجواء ترحيبية للجميع." } },
    { en: { name: "Platinum Pitch", description: "A top-tier venue featuring climate-controlled facilities and premium turf surfaces for the ultimate playing experience." }, ar: { name: "ملعب بلاتينيوم", description: "ملعب من الدرجة الأولى يتميز بمرافق مكيفة ونجيلة فاخرة لتجربة لعب لا مثيل لها." } },
    { en: { name: "Phoenix Sports Park", description: "A modern sports park offering well-maintained pitches and a vibrant community atmosphere for all age groups." }, ar: { name: "حديقة فينيكس الرياضية", description: "حديقة رياضية حديثة توفر ملاعب مميزة وأجواء مجتمعية نابضة بالحياة لجميع الأعمار." } },
    { en: { name: "Horizon Football Club", description: "Experience football at its finest with top-quality grounds, professional staff, and convenient booking options." }, ar: { name: "نادي هورايزون لكرة القدم", description: "استمتع بكرة القدم على أعلى مستوى مع ملاعب عالية الجودة وطاقم محترف وخيارات حجز مريحة." } },
    { en: { name: "Falcon Sports Center", description: "A well-equipped sports center in the heart of the city, offering flexible booking times and multiple ground options." }, ar: { name: "مركز فالكون الرياضي", description: "مركز رياضي مجهز تجهيزاً كاملاً في قلب المدينة، يوفر أوقات حجز مرنة وخيارات ملاعب متعددة." } },
    { en: { name: "Star League Arena", description: "Home to some of the city's best weekly leagues, with floodlit pitches available for late-night matches." }, ar: { name: "أرينا ستار ليج", description: "موطن لبعض من أفضل الدوريات الأسبوعية في المدينة، مع ملاعب مضاءة متاحة للمباريات الليلية." } },
    { en: { name: "Golden Boot Fields", description: "Affordable and accessible, Golden Boot Fields provides quality pitches for casual players and local leagues." }, ar: { name: "ملاعب الحذاء الذهبي", description: "بأسعار معقولة وسهولة الوصول، تقدم ملاعب الحذاء الذهبي ملاعب عالية الجودة للاعبين الهواة والدوريات المحلية." } },
    { en: { name: "Crescent Sports Complex", description: "A spacious and modern complex offering multiple sports facilities, including top-quality football pitches." }, ar: { name: "مجمع الهلال الرياضي", description: "مجمع فسيح وحديث يضم مرافق رياضية متعددة، بما في ذلك ملاعب كرة قدم عالية الجودة." } },
    { en: { name: "Sunrise Football Hub", description: "Open from early morning to late evening, Sunrise Football Hub caters to players with busy schedules." }, ar: { name: "مركز صنرايز لكرة القدم", description: "مفتوح من الصباح الباكر حتى وقت متأخر من الليل، يخدم مركز صنرايز اللاعبين ذوي الجداول المزدحمة." } },
    { en: { name: "Metro Sports Club", description: "Conveniently located near public transport, Metro Sports Club is the go-to destination for city players." }, ar: { name: "نادي مترو الرياضي", description: "يقع في موقع مناسب بالقرب من وسائل النقل العام، ويعد نادي مترو الرياضي الوجهة المفضلة للاعبي المدينة." } },
    { en: { name: "Diamond Arena", description: "An upscale sporting venue with immaculate grounds and premium facilities, perfect for competitive matches." }, ar: { name: "أرينا الماس", description: "ملعب راقٍ بملاعب مميزة ومرافق فاخرة، مثالي للمباريات التنافسية." } },
    { en: { name: "Al Faris Sports Club", description: "A local favourite with a loyal community of players, offering well-kept pitches and a friendly environment." }, ar: { name: "نادي الفارس الرياضي", description: "المفضل المحلي بمجتمع من اللاعبين المخلصين، يوفر ملاعب مميزة وبيئة ودية." } },
    { en: { name: "Olympus Ground", description: "Inspired by champions, Olympus Ground delivers a world-class playing experience with top-tier facilities." }, ar: { name: "ملعب أولمبوس", description: "مستوحى من الأبطال، يقدم ملعب أولمبوس تجربة لعب عالمية المستوى بمرافق من الدرجة الأولى." } },
    { en: { name: "Atlas Football Park", description: "A comprehensive football park with multiple pitches, training areas, and spectator seating for local derbies." }, ar: { name: "حديقة أطلس لكرة القدم", description: "حديقة كرة قدم شاملة بملاعب متعددة ومناطق تدريب ومقاعد للمتفرجين للمباريات المحلية." } },
    { en: { name: "Nile Sports Hub", description: "Situated near the waterfront, Nile Sports Hub combines a scenic location with high-quality football facilities." }, ar: { name: "مركز النيل الرياضي", description: "يقع بالقرب من الواجهة المائية، يجمع مركز النيل الرياضي بين موقع خلاب ومرافق كرة قدم عالية الجودة." } },
    { en: { name: "Royal Sports Complex", description: "A prestigious complex offering exclusive membership options alongside high-quality open-booking pitches." }, ar: { name: "المجمع الرياضي الملكي", description: "مجمع مرموق يوفر خيارات عضوية حصرية إلى جانب ملاعب عالية الجودة مفتوحة للحجز." } },
    { en: { name: "Summit Arena", description: "Reach the peak of your game at Summit Arena, where premium pitches meet professional-grade infrastructure." }, ar: { name: "أرينا سوميت", description: "ارقَ إلى قمة لعبتك في أرينا سوميت، حيث تلتقي الملاعب المتميزة بالبنية التحتية الاحترافية." } },
    { en: { name: "Spark Football Center", description: "A dynamic and energetic venue that hosts weekly leagues, tournaments, and open sessions for all skill levels." }, ar: { name: "مركز سبارك لكرة القدم", description: "ملعب ديناميكي وحيوي يستضيف الدوريات الأسبوعية والبطولات والجلسات المفتوحة لجميع المستويات." } },
    { en: { name: "Al Masry Sports Park", description: "A heritage venue with modern upgrades, serving the local community with quality pitches and affordable rates." }, ar: { name: "حديقة المصري الرياضية", description: "ملعب تراثي بتحديثات حديثة، يخدم المجتمع المحلي بملاعب عالية الجودة وأسعار معقولة." } },
    { en: { name: "Prestige Football Club", description: "An exclusive club offering members-only access to some of the finest football pitches in the region." }, ar: { name: "نادي بريستيج لكرة القدم", description: "نادٍ حصري يوفر وصولاً خاصاً بالأعضاء إلى بعض من أفضل ملاعب كرة القدم في المنطقة." } },
    { en: { name: "Velocity Sports Arena", description: "Fast-paced and action-packed, Velocity Sports Arena is built for players who love the game at full intensity." }, ar: { name: "أرينا فيلوسيتي الرياضية", description: "سريعة الإيقاع ومليئة بالإثارة، صُممت أرينا فيلوسيتي الرياضية للاعبين الذين يحبون اللعبة بأقصى حدة." } },
    { en: { name: "Triumph Ground", description: "Built for winners, Triumph Ground features competition-ready pitches and a motivating sporting atmosphere." }, ar: { name: "ملعب الانتصار", description: "مصمم للفائزين، يتميز ملعب الانتصار بملاعب جاهزة للمنافسة وأجواء رياضية محفزة." } },
    { en: { name: "Zenith Sports Club", description: "Reach new heights at Zenith Sports Club, where every detail is designed to elevate your playing experience." }, ar: { name: "نادي زينيث الرياضي", description: "ارتقِ إلى آفاق جديدة في نادي زينيث الرياضي، حيث تم تصميم كل تفصيلة لرفع مستوى تجربتك الرياضية." } },
    { en: { name: "Heritage Football Park", description: "A community-centered venue with deep local roots, offering welcoming pitches for players of all backgrounds." }, ar: { name: "حديقة هيريتيج لكرة القدم", description: "ملعب يمثل قلب المجتمع بجذور محلية عميقة، يوفر ملاعب ترحيبية للاعبين من جميع الخلفيات." } },
    { en: { name: "Apex Football Center", description: "A premier football facility with world-class pitches, offering the ultimate environment for training and matches." }, ar: { name: "مركز أبيكس لكرة القدم", description: "مرفق كرة قدم من الدرجة الأولى بملاعب عالمية المستوى، يوفر البيئة المثلى للتدريب والمباريات." } },
    { en: { name: "Coastal Sports Hub", description: "Enjoy football with a sea breeze at Coastal Sports Hub, one of Alexandria's most scenic sporting destinations." }, ar: { name: "مركز الساحل الرياضي", description: "استمتع بكرة القدم مع نسيم البحر في مركز الساحل الرياضي، إحدى أجمل الوجهات الرياضية في الإسكندرية." } },
];

export default pitches;
