/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AppProductRouteImport } from './routes/_app/product'
import { Route as AppOwnersRouteImport } from './routes/_app/owners'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AuthVerifyIndexRouteImport } from './routes/auth/verify/index'
import { Route as AuthResetIndexRouteImport } from './routes/auth/reset/index'
import { Route as AuthVerifySendRouteImport } from './routes/auth/verify/send'
import { Route as AuthResetSendRouteImport } from './routes/auth/reset/send'
import { Route as AppPitchesSearchIndexRouteImport } from './routes/_app/pitches/search/index'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductRoute = AppProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOwnersRoute = AppOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthVerifyIndexRoute = AuthVerifyIndexRouteImport.update({
  id: '/auth/verify/',
  path: '/auth/verify/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetIndexRoute = AuthResetIndexRouteImport.update({
  id: '/auth/reset/',
  path: '/auth/reset/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerifySendRoute = AuthVerifySendRouteImport.update({
  id: '/auth/verify/send',
  path: '/auth/verify/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthResetSendRoute = AuthResetSendRouteImport.update({
  id: '/auth/reset/send',
  path: '/auth/reset/send',
  getParentRoute: () => rootRouteImport,
} as any)
const AppPitchesSearchIndexRoute = AppPitchesSearchIndexRouteImport.update({
  id: '/pitches/search/',
  path: '/pitches/search/',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/contact': typeof AppContactRoute
  '/owners': typeof AppOwnersRoute
  '/product': typeof AppProductRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/reset/send': typeof AuthResetSendRoute
  '/auth/verify/send': typeof AuthVerifySendRoute
  '/auth/reset/': typeof AuthResetIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/pitches/search/': typeof AppPitchesSearchIndexRoute
}
export interface FileRoutesByTo {
  '/contact': typeof AppContactRoute
  '/owners': typeof AppOwnersRoute
  '/product': typeof AppProductRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/': typeof AppIndexRoute
  '/auth/reset/send': typeof AuthResetSendRoute
  '/auth/verify/send': typeof AuthVerifySendRoute
  '/auth/reset': typeof AuthResetIndexRoute
  '/auth/verify': typeof AuthVerifyIndexRoute
  '/pitches/search': typeof AppPitchesSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_app/contact': typeof AppContactRoute
  '/_app/owners': typeof AppOwnersRoute
  '/_app/product': typeof AppProductRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/_app/': typeof AppIndexRoute
  '/auth/reset/send': typeof AuthResetSendRoute
  '/auth/verify/send': typeof AuthVerifySendRoute
  '/auth/reset/': typeof AuthResetIndexRoute
  '/auth/verify/': typeof AuthVerifyIndexRoute
  '/_app/pitches/search/': typeof AppPitchesSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contact'
    | '/owners'
    | '/product'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/reset/send'
    | '/auth/verify/send'
    | '/auth/reset/'
    | '/auth/verify/'
    | '/pitches/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/contact'
    | '/owners'
    | '/product'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/'
    | '/auth/reset/send'
    | '/auth/verify/send'
    | '/auth/reset'
    | '/auth/verify'
    | '/pitches/search'
  id:
    | '__root__'
    | '/_app'
    | '/_app/contact'
    | '/_app/owners'
    | '/_app/product'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/_app/'
    | '/auth/reset/send'
    | '/auth/verify/send'
    | '/auth/reset/'
    | '/auth/verify/'
    | '/_app/pitches/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthResetSendRoute: typeof AuthResetSendRoute
  AuthVerifySendRoute: typeof AuthVerifySendRoute
  AuthResetIndexRoute: typeof AuthResetIndexRoute
  AuthVerifyIndexRoute: typeof AuthVerifyIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/product': {
      id: '/_app/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof AppProductRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/owners': {
      id: '/_app/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AppOwnersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/auth/verify/': {
      id: '/auth/verify/'
      path: '/auth/verify'
      fullPath: '/auth/verify/'
      preLoaderRoute: typeof AuthVerifyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset/': {
      id: '/auth/reset/'
      path: '/auth/reset'
      fullPath: '/auth/reset/'
      preLoaderRoute: typeof AuthResetIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verify/send': {
      id: '/auth/verify/send'
      path: '/auth/verify/send'
      fullPath: '/auth/verify/send'
      preLoaderRoute: typeof AuthVerifySendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/reset/send': {
      id: '/auth/reset/send'
      path: '/auth/reset/send'
      fullPath: '/auth/reset/send'
      preLoaderRoute: typeof AuthResetSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/pitches/search/': {
      id: '/_app/pitches/search/'
      path: '/pitches/search'
      fullPath: '/pitches/search/'
      preLoaderRoute: typeof AppPitchesSearchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppContactRoute: typeof AppContactRoute
  AppOwnersRoute: typeof AppOwnersRoute
  AppProductRoute: typeof AppProductRoute
  AppIndexRoute: typeof AppIndexRoute
  AppPitchesSearchIndexRoute: typeof AppPitchesSearchIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppContactRoute: AppContactRoute,
  AppOwnersRoute: AppOwnersRoute,
  AppProductRoute: AppProductRoute,
  AppIndexRoute: AppIndexRoute,
  AppPitchesSearchIndexRoute: AppPitchesSearchIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthResetSendRoute: AuthResetSendRoute,
  AuthVerifySendRoute: AuthVerifySendRoute,
  AuthResetIndexRoute: AuthResetIndexRoute,
  AuthVerifyIndexRoute: AuthVerifyIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
