/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as appIndexRouteImport } from './routes/(app)/index'
import { Route as PitchesSearchRouteImport } from './routes/pitches/search'
import { Route as appProductRouteImport } from './routes/(app)/product'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const appIndexRoute = appIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRouteRoute,
} as any)
const PitchesSearchRoute = PitchesSearchRouteImport.update({
  id: '/pitches/search',
  path: '/pitches/search',
  getParentRoute: () => rootRouteImport,
} as any)
const appProductRoute = appProductRouteImport.update({
  id: '/product',
  path: '/product',
  getParentRoute: () => appRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/product': typeof appProductRoute
  '/pitches/search': typeof PitchesSearchRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesByTo {
  '/product': typeof appProductRoute
  '/pitches/search': typeof PitchesSearchRoute
  '/': typeof appIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/product': typeof appProductRoute
  '/pitches/search': typeof PitchesSearchRoute
  '/(app)/': typeof appIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/product' | '/pitches/search' | '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/product' | '/pitches/search' | '/'
  id: '__root__' | '/(app)' | '/(app)/product' | '/pitches/search' | '/(app)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRouteRoute: typeof appRouteRouteWithChildren
  PitchesSearchRoute: typeof PitchesSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/': {
      id: '/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof appIndexRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/pitches/search': {
      id: '/pitches/search'
      path: '/pitches/search'
      fullPath: '/pitches/search'
      preLoaderRoute: typeof PitchesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/product': {
      id: '/(app)/product'
      path: '/product'
      fullPath: '/product'
      preLoaderRoute: typeof appProductRouteImport
      parentRoute: typeof appRouteRoute
    }
  }
}

interface appRouteRouteChildren {
  appProductRoute: typeof appProductRoute
  appIndexRoute: typeof appIndexRoute
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appProductRoute: appProductRoute,
  appIndexRoute: appIndexRoute,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  appRouteRoute: appRouteRouteWithChildren,
  PitchesSearchRoute: PitchesSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
